Review
elenaplehanova/s-chistogo-lista pull request #3
Opened 2024-09-14 03:00 UTC by elenaplehanova

2024-09-14 05:48 UTC, seginel requested changes
Здравствуйте, У вас получилась хорошая работа, но в ней есть замечания - здесь понадобятся доработки.

### Что понравилось

* Аккуратное форматирование кода
* Используются сематические теги
* Размечена вся структура
* Страница визуально похожа на макет
* Страница валидна
* Правильно оформлен head

### Что нужно поправить

* Все комментарии "Надо исправить" в коде.
* После внесения правок проверьте код в валидаторе https://validator.w3.org/nu/#textarea, там не должно быть критических ошибок типа ERROR. При наличии ошибок - их нужно проанализировать и исправить (если эта ошибка не противоречит другим пунктам в чеклиста к проекту).
* Стоит напомнить, что все замечания не придумываются ревьюером на ходу. Они формируются на основе чеклиста и брифа к заданию. Если соблюсти все требования чеклиста и рекомендаций в брифе, то работа будет сразу же принята. Поэтому перед отправкой на следующую итерацию рекомендую самостоятельно пройтись по брифу и чеклисту и при необходимости поправить все проблемные места. Это позволит быстрее получить зачёт по работе.

### Что можно лучше

* Все комментарии "Можно лучше" в коде.

Комментарии "можно лучше" носят рекомендательный характер, их выполнение остается на Ваше усмотрение. Комментарии "надо исправить" являются обязательными, при выполнении всех "надо исправить" работа будет зачтена. Удачи

2024-09-14 05:48 UTC, seginel commented on index.html
> +        <h1>
Отлично. Это основной заголовок страницы. Для него верно выбран тег первого уровня. Помните, что заголовок первого уровня может быть только один на странице.

2024-09-14 05:48 UTC, seginel commented on index.html
> +          <time class="intro__date" datetime="2022-06-05">05.06.2022 г.</time>
Отлично - использован подходящий семантический тег

2024-09-14 05:48 UTC, seginel commented on index.html
> +        <div class="content-section__introduction">
Надо исправить: 
div используется для разметки. Для текстовых фрагментов используйте тег параграфа `<p>`

2024-09-14 05:48 UTC, seginel commented on index.html
> +        <div class="content-section__introduction">
Надо исправить: 
div используется для разметки. Для текстовых фрагментов используйте тег параграфа `<p>`

2024-09-14 05:48 UTC, seginel commented on index.html
> +                <div class="card__text">
Надо исправить: 
div используется для разметки. Для текстовых фрагментов используйте тег параграфа `<p>`

2024-09-14 05:48 UTC, seginel commented on styles/style.css
> +  height: 100px;
Надо исправить: 
Не следует ограничивать высоту блока, внутри которого есть какое-то содержимое. Размер, количество элементов или количество текста внутри может измениться, контейнер при этом должен гибко реагировать на изменение объема контента.

2024-09-14 05:48 UTC, seginel commented on styles/style.css
> +  background-position: 10px 20px 30px 40px;
Надо исправить: 
1) Строка написана с ошибкой, у позиции фона может быть только 1 или 2 значения, так как фон выставляется только по двум осям - X и Y. Такие строки браузер зачёркивает https://disk.yandex.ru/i/0thmtwobKVjvhA , так как не может их интерпретировать
2) В одном CSS-правиле не должны повторяться свойства. Свойства для позиционирования фона указаны здесь и ниже

2024-09-14 05:48 UTC, seginel commented on styles/style.css
> +.accent-span_color-dark {
Надо исправить:
1) классы должны быть подходящими и использоваться по назначению. Имя класса подразумевает, что здесь будут стили для тёмного текста (color-dark). А так как все классы должны быть переиспользуемыми, то нам может понадобится применить этот класс в любом другом месте на сайте. Однако вместе с цветом окажется, что у этого класса задан ещё и размер шрифта. Так делать не стоит. У этого класса оставьте только стилизацию, которая определяет цветовую составляющую шрифта

2) Согласно чеклисту `Стили одинаковых элементов не дублируются, а переиспользуются.`  Здесь два заголовка : https://disk.yandex.ru/i/hnPPmFjfFnp5fw - они отличаются лишь цветом, в остальном это одинаковые элементы для озаглавливания. И для одинаковых элементов дублируются стили в разных классах: https://disk.yandex.ru/i/cEZyyaw7NV8hXA 

**Здесь можно создать отдельный класс для задания размера шрифта, но я бы порекомендовал поступить другим способом: оба эти заголовка имеют общий класс `content-section__subtitle` и именно для этого класса имеет смысл задать шрифт, размер шрифта, высоту строки. А для `.accent-span_color-***`**  оставить цвет и `display: block`

2024-09-14 05:48 UTC, seginel commented on styles/style.css
> +.card__author-photo {
Можно лучше: 
Картинка может приходить квадратной без обрезанных краёв. Здесь не мешало бы добавить скругление через `border-radius: 50%` https://doka.guide/css/border-radius/

2024-09-14 05:48 UTC, seginel commented on styles/style.css
> +.footer__menu-list {
Надо исправить.
В блоке ссылок в футере не указан размер шрифта. 
При наложении макета есть расхождения из-за этого (так как размер шрифта по умолчанию не соответствует размеру шрифта по макету)
https://disk.yandex.ru/i/fcidSOOtSRaHpg

2024-09-14 05:48 UTC, seginel commented on index.html
> +  </head>
Отлично - head заполнен корректно

2024-09-15 04:54 UTC, elenaplehanova commented
Добрый день! 
Спасибо за комментарии. Учту на бедующее )

2024-09-15 08:26 UTC, seginel approved these changes
Спасибо за правки. Вы внесли исправления по замечаниям и хочу поздравить - Вы отлично справились с выполнением проектной работы. В работе осталось одно неисправленное замечания, отметил его повторно. 
В остальном по странице у меня больше нет замечаний: страница соответствует макету и требованиям чеклиста.
Работу принимаю. Удачи в дальнейшем обучении.

2024-09-15 08:26 UTC, seginel commented on styles/style.css
> +  height: 100px;
Замечание не исправлено. Здесь достаточно просто убрать строку со свойством height.

2024-09-16 02:43 UTC, merged